
exclude:
  - bin
  - README.md
keep_files:
  - '2006-03-stones-jfk'
  - '2006-03-tour-of-california'
  - '2006-04-hummingbird'
  - '2006-07-becoming-a-homeowner'
  - '2007-08-dont-try-and-run'
  - '2007-08-home-theater'
  - '2007-11-impeach-cheney-meeting-my-hero'
  - '2008-03-training-to-bike-first-aids-lifecycle-sf-to-la'
  - '2008-04-bike-gears-jamming-a-triple-into-a-double'
  - '2008-06-aids-lifecycle'
  - '2009-03-traceys-new-domain-and-website'
  - '2009-04-breakfast-with-amy-goodman-of-democracy-now'
  - '2009-04-ffmpeg-building-on-mac-intelx386'
  - '2009-05-its-ok-to-be-a-trl'
  - '2009-05-tracey-bike-accident-walks-away-scraped-but-ok'
  - '2009-06-finished-the-ride'
  - '2009-06-halfway-through-aids-lifecycle'
  - '2009-06-rain-delay-at-start-day6'
  - '2009-06-starting-day-6-2'
  - '2009-06-thank-you-donors'
  - '2009-09-ffmpeg-for-time-lapse-sets-of-images-and-even-archiving'
  - '2010-04-star-wars-re-remastered-to-high-quality-1977-version'
  - '2010-06-great-frontline-program-the-wounded-platoon'
  - '2010-06-kitty-shot'
  - '2010-06-updated-site'
  - '2010-09-another-great-indie-film'
  - '2010-09-marine-layer-in-bay-area'
  - '2010-10-sony-p-series-running-10-10-meerkat-ubuntu'
  - '2010-11-amazing-summer-trip-to-bali'
  - '2011-03-its-fun-to-drink-and-drive'
  - '2011-04-fun-with-ford-gt-in-gt5'
  - '2011-04-internet-archive-holiday-party-time-lapse'
  - '2011-04-the-train-from-spain-rides-mainly-on-the-plane'
  - '2011-05-awesome-artwork'
  - '2011-05-ifone2-lockup'
  - '2011-05-natively-compiling-ffmpeg-x264-mplayer-on-mac-with-builtin-x264-and-webm-encoding'
  - '2011-05-star-wars-1977-reedit-night'
  - '2011-05-star-wars-steampunk-amazing-art'
  - '2011-06-mole-rolls-to-freedom'
  - '2011-07-bloviate'
  - '2011-09-drifting-lotus-elise-on-playstation'
  - '2011-09-return-to-alma-mater'
  - '2011-10-domain-change'
  - '2011-10-double-awesome-art-in-financial-district'
  - '2011-10-laundry-for-the-empire'
  - '2011-10-more-books-for-internet-archive'
  - '2011-11-birthday-hike'
  - '2011-11-bitchn-camaro'
  - '2011-11-cute-scion-iq-coming-to-states'
  - '2011-12-camaro-0-to-60-test'
  - '2012-01-iphone-and-external-mic-sennheiser-mke-400-can-rule-the-galaxy'
  - '2012-01-natively-compiling-ffmpeg-mplayer-mencoder-on-macos-lion-with-x264'
  - '2012-02-deinterlacing-2323-telecine-video-into-fields-for-visual-analysis'
  - '2012-02-my-town-1947-style'
  - '2012-04-fun-bootie-mashup-dance-mix'
  - '2012-04-google-maps-upgrades-to-8-bit-hi-res-today-8'
  - '2012-05-luke-battling-darth-ascii'
  - '2012-06-convert-yuvj420p-to-yuv420p-chrome-playable-mp4-video-eg-canonnikon-video'
  - '2012-06-luke-battling-darth-ascii-green'
  - '2012-09-friday-beer-options'
  - '2012-09-on-to-rafting-adventure-long-weekend-via-salt-lake'
  - '2012-09-shuttle-endeavour-flies-by-us-by-golden-gate-today-twice'
  - '2012-10-decaf-honda-cb400a-replacement-consolidated-speedometer-ordered'
  - '2012-10-decaf-honda-cb500-automatic-cafe-racer-ive-been-a-bad-girl-today'
  - '2012-10-replacing-cb400a-instruments-to-smaller-cafe-racer-style'
  - '2012-11-decaf-1978-honda-cb400a-speedometer-and-instruments-replaced'
  - '2012-11-honda-cb400a-fixing-turn-signal-and-neutral-leds-to-new-speedometer'
  - '2012-11-test-fit-of-decaf-cb400a-smaller-speedometer-instrument-lights'
  - '2012-12-decaf-cb400a-reassembled-and-on-the-cruise'
  - '2013-01-decaf-1978-honda-cb400a-running-and-instruments-working'
  - '2013-02-how-to-turn-time-machine-from-disk-with-many-partitions-to-single-partition-logically-extending-time-machine-partition'
  - '2013-02-morgan-territory-motorcyclin-85-mile-east-bay-loop-around-mt-diablo-with-honda-cb400a-decaf'
  - '2013-02-new-php-htm-mode-for-emacs-intermixed-php-html-js-and-css-using-multi-modes'
  - '2013-02-simple-way-to-make-h-264-mp4-web-and-iosmobile-playable-video-mp4-files-for-linux-and-macosx-using-ffmpeg'
  - '2013-02-today-i-did-my-first-oil-and-oil-filter-change-ever-honda-cb400a-decaf'
  - '2013-04-made-my-own-heat-duct-reducer-today-for-25-in-only-two-hours'
  - '2013-06-how-to-stop-indoor-cat-pee'
  - '2013-07-anthony-weiner-lewd-texting-after-leaving-politics'
  - '2013-08-vietnam-vader-helmet'
  - '2013-09-new-bay-bridge-span-opens-vlog-1st-person-motorcycle-ride-across'
  - '2013-10-time-lapse-overlooking-the-san-francisco-bay-on-labor-day-with-a-150-foot-tree-removal'
  - '2013-10-wow-that-was-2011-3-wyden'
  - '2013-11-play-motion-jpeg-video-using-javascript-in-browser-no-plugins-minimal-js'
  - '2013-12-puzzle-classic-game-with-css-and-js'
  - '2014-05-decaf-front-brake-fix-fluid-flush-and-bleed-1978-honda-cb-400a'
  - '2014-09-hyper-green-magic-green-magic-man-kawasaki-zx-6-motorcycle-hyperlapse-route-1-ca'
  - '2014-12-rejoice-the-angel-poohbot-brings-you-good-tidings'
  - '2015-02-embeddable-book-from-my-work'
  - '2015-05-slide-responsively-minimal-standalone-htmcssjs-inspired-by-sliding-door-from-wayne-connor'
  - '2015-06-hacking-apple-watch-to-a-cuff-bracelet-custom-watch'
  - '2015-08-fixing-1978-honda-cb400a-always-on-neutral-light-decaf-project-bike'
  - '2015-09-save-the-decaf-rebuilding-and-renewing-the-engine-of-1978-cb400a-honda-motorcycle-named-decaf'
  - '2017-08-arkit-beta-excitement-building'
  - '2017-08-house-remodel-sketchup-3d-vr-model-visualized-on-sketchfab'
  - '2017-08-walk-through-sketchup-large-models-in-arkit-perfect-for-home-remodels-and-projects'
  - '2017-09-responsive-masonic-tiles-using-css-grid-no-js-no-flexbox'
  - '2018-03-recursion-which-is-a-way-to-call-yourself-via-recursion-which-is-a-way-to-call-yourself-via-recursion'
  - '2018-06-star-words-star-wars-trilogy-scripts-word-cloud'
  - '2019-03-something-petabox-tree'
  - '2019-06-house-design-railing'
  - '2019-08-meesa-3-k8s-annie'
  - '2019-09-techo-tuesday-javascript-es6-and-es-modules'
  - '2019-09-techo-tuesday-make-a-free-website-static-site-generators-and-hugo'
  - '2019-10-techo-tuesday-dark-mode'
  - '2020-02-hunter-birthday-50'
  - '2020-05-techo-tuesday-javascript-es-modules-test-and-coverage-without-babel'
  - '2020-07-like-kubernetes-k3s-is-dead-on-floor-fast'
  - '2020-11-dutch-appeltart-pie'
  - '2021-04-vscode-in-browser--for-mobile-and-more'
  - '2021-12-deno-oh-my-gawd-deno'
  - '2022-01-gravel-bikes'
  - '2022-01-traceys-tamalpais-thirty-3t'
  - 'CNAME'
  - 'config.json'
  - 'css'
  - 'img'
  - 'index.html'
  - 'js'
  - 'robots.txt'
  - 'sitemap.xml'
  - 'theme.js'
