title: Tracey Jaquith - blogtini
user: traceypooh
repo: blogtini
git_provider: github # github or gitlab
img_site: img/traceymonet-half.jpg
posts_per_page: 10
remove_blur: true

intro:
  paragraph: "Technophile · Optimist · <a href=/biking>Cyclist</a> · <a href=https://archive.org/about/bios.php>Archivist</a> · Design · <a href=/video>Video</a> · TV · Nomad · Docker"

sidebar:
  about: tracey is a nonstop dance party.  so you dont have to.  dont ask me about <a href=/2019-08-meesa-3-k8s-annie/>containers</a>.  thanks for dropping by today.  you look nice.
  post_amount: 5
  # set to show or to hide categories in the sidebar
  categories: true
  # Sets Categories to sort by number of posts instead of alphabetical
  categories_by_count: true

social:
  twitter: tracey_pooh
  youtube: channel/UCBcfKCrYjtWcuTk5LLT-7xg
  linkedin: tracey-jaquith-929432
  pinterest: poohbot
  github: traceypooh
  gitlab: traceypooh
  codepen: traceypooh
  stackoverflow: 11941875 # User Number
  flickr: 46222920@N05
  tumblr: traceypooh
  strava: traceypooh



staticman:
  # If using GitHub, go to https://github.com/apps/staticman-net
  # If using GitLab, just add the GitLab bot, NO need to hit `/connect/v3/...`
  enabled:  true
  api:      traceypooh-staticman.dev.archive.org  # without trailing slash, defaults to "staticman3.herokuapp.com"
  branch:   main
